# dataset params
dataset: 'tiny'
classes: 200

# model params
model_type: 'EDM'
net_type: 'UNetC'
diffusion:
  sigma_data: 0.5
  p_mean: -1.2
  p_std: 1.2
  sigma_min: 0.002
  sigma_max: 80
  rho: 7
  S_min: 0.01
  S_max: 1
  S_noise: 1.007
network:
  image_shape: [3, 64, 64]
  n_channels: 128
  ch_mults: [1, 2, 2, 2]
  is_attn: [False, False, True, False]
  dropout: 0.1
  n_blocks: 5 # equiv. to "n_blocks=4" in UNetHo + "use BigGAN up/down"

# training params
n_epoch: 2000
batch_size: 192
lrate: 1.5e-4
warm_epoch: 200
load_epoch: -1
flip: False
ema: 0.9993
# optim: 'Adam'
# optim_args:
#   betas: [0.9, 0.99]

# testing params
n_sample: 30
save_dir: './output_Ctiny'
save_model: True

# linear probe
linear:
  n_epoch: 15
  batch_size: 128
  lrate: 1.0e-3
  timestep: 5
  blockname: 'out_6'
