# dataset params
dataset: 'cifar100'
classes: 100

# model params
model_type: 'EDM'
net_type: 'UNetC'
diffusion:
  sigma_data: 0.5
  p_mean: -1.2
  p_std: 1.2
  sigma_min: 0.002
  sigma_max: 80
  rho: 7
  S_min: 0.01
  S_max: 1
  S_noise: 1.007
network:
  image_shape: [3, 32, 32]
  n_channels: 128
  ch_mults: [1, 2, 2, 2]
  is_attn: [False, True, False, False]
  dropout: 0.13
  n_blocks: 3 # equiv. to "n_blocks=2" in UNetHo + "use BigGAN up/down"

# training params
n_epoch: 1000
batch_size: 512
lrate: 4.0e-4
warm_epoch: 200
load_epoch: -1
flip: True
ema: 0.9993
# optim: 'Adam'
# optim_args:
#   betas: [0.9, 0.99]

# testing params
n_sample: 30
save_dir: './output_C100'
save_model: True

# linear probe
linear:
  n_epoch: 15
  batch_size: 128
  lrate: 1.0e-3
  timestep: 4
  blockname: 'out_6'
